### ISSUE TITLE
how to install in 0.19 or 0.20?

### ISSUE THREAD

**Issue by JuanJ67m** [OpenCollaborationPlatform/CollaborativeFC#7]
I did not find any method to install in both versions.

**Comment by ickby** [comment]
Did you follow the description in https://forum.freecadweb.org/viewtopic.php?f=8&t=57028? Basically it should work via the addon installer within free-cad. If not please give me more details on what fails, so that I can use this information to refine the process.

**Comment by ickby** [comment]
I copied the installation instruction into the readme for easier access via github

**Comment by luzpaz** [comment]
Looks good. Ticket can be closed

**Comment by ickby** [comment]
yeah good idea. It can be reopened if still unclear to someone.
