### ISSUE TITLE
Add Known Issues to the README

### ISSUE THREAD

**Issue by luzpaz** [OpenCollaborationPlatform/CollaborativeFC#9]
Help orient people where the main issues are and what to expect

**Comment by ickby** [comment]
Good idea. I currently work on a big set of changes, that improve many current problems. I leave the issue open and add a list when those are merged, should be in the next 1-2 months.

**Comment by luzpaz** [comment]
https://github.com/OpenCollaborationPlatform/CollaborativeFC#alpha-state-limitations  
Nice!
